// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaRwhaUo3ncJZy4MthavVJMJeBRWPLIVQ',
    appId: '1:988578521519:web:408b54f709d9fc88890f5a',
    messagingSenderId: '988578521519',
    projectId: 'techwiz-app-ec16f',
    authDomain: 'techwiz-app-ec16f.firebaseapp.com',
    databaseURL: 'https://techwiz-app-ec16f-default-rtdb.firebaseio.com',
    storageBucket: 'techwiz-app-ec16f.appspot.com',
    measurementId: 'G-7DCC8ZNHVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuOkWCue55_QD3ETFzXh90W10wms5jNRE',
    appId: '1:988578521519:android:0a91d6fa38946039890f5a',
    messagingSenderId: '988578521519',
    projectId: 'techwiz-app-ec16f',
    databaseURL: 'https://techwiz-app-ec16f-default-rtdb.firebaseio.com',
    storageBucket: 'techwiz-app-ec16f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA26g81ntSR3cIuDwy57Ahid3vWhqxnJ3Q',
    appId: '1:988578521519:ios:aa64c147d94356c7890f5a',
    messagingSenderId: '988578521519',
    projectId: 'techwiz-app-ec16f',
    databaseURL: 'https://techwiz-app-ec16f-default-rtdb.firebaseio.com',
    storageBucket: 'techwiz-app-ec16f.appspot.com',
    androidClientId: '988578521519-oh0347700ioghgl5e5jehnhml8mkkhoj.apps.googleusercontent.com',
    iosClientId: '988578521519-c0526t3e09eb9nfhe4r1na5iad0f802n.apps.googleusercontent.com',
    iosBundleId: 'com.example.techwiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA26g81ntSR3cIuDwy57Ahid3vWhqxnJ3Q',
    appId: '1:988578521519:ios:aa64c147d94356c7890f5a',
    messagingSenderId: '988578521519',
    projectId: 'techwiz-app-ec16f',
    databaseURL: 'https://techwiz-app-ec16f-default-rtdb.firebaseio.com',
    storageBucket: 'techwiz-app-ec16f.appspot.com',
    androidClientId: '988578521519-oh0347700ioghgl5e5jehnhml8mkkhoj.apps.googleusercontent.com',
    iosClientId: '988578521519-c0526t3e09eb9nfhe4r1na5iad0f802n.apps.googleusercontent.com',
    iosBundleId: 'com.example.techwiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaRwhaUo3ncJZy4MthavVJMJeBRWPLIVQ',
    appId: '1:988578521519:web:37e5ce88267f976c890f5a',
    messagingSenderId: '988578521519',
    projectId: 'techwiz-app-ec16f',
    authDomain: 'techwiz-app-ec16f.firebaseapp.com',
    databaseURL: 'https://techwiz-app-ec16f-default-rtdb.firebaseio.com',
    storageBucket: 'techwiz-app-ec16f.appspot.com',
    measurementId: 'G-0FC0R6J570',
  );
}
